const projects = {
  "provenia-bio": {number:"01",category:"Biomedical AI",title:"Provenia Bio",accent:"#dbe8ed",summary:"A proof- and provenance-carrying neuro-symbolic drug-discovery system for auditable therapeutic hypothesis generation.",tags:["Neuro-symbolic AI","Drug Discovery","PROV-O","FastAPI"],repo:"https://github.com/zoraizmohammad/provenia-bio",problem:"Drug-discovery systems can produce plausible hypotheses without exposing the evidence, transformations, or uncertainty behind them.",approach:"Provenia pairs every promoted hypothesis with machine-checkable proofs, W3C PROV traces, validation gates, and calibrated uncertainty.",steps:["Ingest evidence","Compose hypothesis","Validate proof","Publish provenance"],principles:[["Evidence before confidence","Claims remain attached to their sources."],["Machine-checkable promotion","Validation gates decide what advances."],["Explicit uncertainty","Confidence is measured rather than implied."],["Auditable lineage","Every transformation remains traceable."]],status:"The page establishes the system contract and is ready for proof traces, model diagrams, and validation results.",next:"targetonco"},
  targetonco: {
    number:"02", category:"Precision Oncology", title:"TargetONCO", accent:"#dcefe5",
    summary:"An agentic precision-oncology platform turning radiology, spatial proteomics, vector search, and report generation into one traceable cancer-analysis workflow.",
    tags:["Python","FastAPI","React","Elasticsearch"], repo:"https://github.com/zoraizmohammad/targetONCO",
    problem:"Clinical and research teams often work across disconnected imaging, tissue, literature, and reporting tools. TargetONCO explores a single workspace in which those signals can be assembled into an evidence-backed differential without hiding how the system reached it.",
    approach:"The system coordinates specialized analysis stages instead of asking one model to do everything. Imaging and proteomic outputs become structured evidence, retrieval adds relevant context, and an agentic layer assembles the final reasoning trail for review.",
    steps:["Radiology + tissue inputs","Specialized ML analysis","Clinical vector retrieval","Ranked report + evidence"],
    principles:[["Multimodal by design","Treat imaging, spatial biology, and retrieved evidence as complementary signals."],["Human review stays central","Present rankings and evidence as decision support—not an autonomous diagnosis."],["Traceable outputs","Keep source context attached as information moves through the workflow."],["Composable pipeline","Allow individual models, indexes, and reporting stages to evolve independently."]],
    status:"This first project page establishes the intended end-to-end workflow and the product narrative. Future iterations can add real interface captures, an architecture diagram, validation methodology, and example reports.", next:"quantum-bayesian-learner"
  },
  "quantum-bayesian-learner": {
    number:"03", category:"Quantum Systems", title:"Quantum Bayesian Learner", accent:"#f4d9d4",
    summary:"A hardware-aware quantum learning system that studies how Bayesian evidence updates and variational circuits behave under realistic circuit-cost constraints.",
    tags:["Qiskit","JAX","FakeManila","QML"], repo:"https://github.com/zoraizmohammad/qb-learner-compression",
    problem:"Quantum models are often evaluated in idealized settings where accuracy is separated from the cost of running a circuit on real hardware. This project treats predictive behavior and deployability as part of the same optimization problem.",
    approach:"Exact statevector and density-matrix cores provide a controlled baseline. Candidate entanglers are then pruned, transpiled against a hardware model, and compared through learned-versus-random mask ablations.",
    steps:["Bayesian evidence","Variational circuit","Greedy mask pruning","Hardware-aware evaluation"],
    principles:[["Exact baselines","Use controlled simulation to understand behavior before adding hardware effects."],["Cost after transpilation","Measure the circuit the device would see, not only the abstract ansatz."],["Ablate the mask","Compare learned pruning with random masks to isolate where gains originate."],["Reproducible sweeps","Keep configurations and evaluation paths explicit for repeatable experiments."]],
    status:"The starter page frames the research question and evaluation loop. It is ready for equations, compression curves, circuit visualizations, and a concise results table when those artifacts are selected.", next:"ombench"
  },
  ombench: {
    number:"04", category:"Agent Memory", title:"Ombench", accent:"#dbe0e5",
    summary:"A memory and backtesting platform for operational agents, designed to measure whether accumulated context improves performance on work that already happened.",
    tags:["Python","Agents","Backtesting","Chroma"], repo:"https://github.com/zoraizmohammad/ombench",
    problem:"Agent memory is easy to demo and difficult to evaluate. More stored context does not necessarily produce better decisions, and live tasks rarely provide a stable baseline for measuring improvement.",
    approach:"Ombench captures task history, compiles durable memories, and replays historical work across communication and productivity tools. The same task can be evaluated with and without memory to make its contribution observable.",
    steps:["Capture work history","Compile durable memory","Replay past tasks","Compare agent outcomes"],
    principles:[["Replay over anecdotes","Evaluate on repeatable historical scenarios rather than isolated demos."],["Memory is a hypothesis","Test whether each memory strategy helps instead of assuming more context is better."],["Operational realism","Model the cross-tool environment in which working agents actually operate."],["Inspectability","Make retrieved memories and their influence visible during analysis."]],
    status:"This layout is prepared for benchmark definitions, replay traces, memory examples, and comparison plots. The initial copy focuses on the core evaluation idea and avoids claiming results before they are documented.", next:"agentic-pollination-uav"
  },
  qadam:{number:"05",category:"Accessible Biotech",title:"Qadam",accent:"#efdfb9",summary:"A portable, offline-first prosthetics clinic built around reusable fitting tools, open hardware, and affordable mechanical limbs.",tags:["Open Hardware","Prosthetics","Accessibility"],repo:"https://github.com/zoraizmohammad/qadam",problem:"Traditional prosthetics delivery depends on expensive equipment, specialist facilities, and supply chains that are unavailable in many communities.",approach:"Qadam packages fitting, fabrication guidance, records, and reusable clinical tools into a field-deployable system.",steps:["Assess patient","Capture fit","Configure limb","Deliver + follow up"],principles:[["Design for the field","Assume constrained power and connectivity."],["Keep tools reusable","Reduce recurring cost and waste."],["Open the hardware","Make local repair and adaptation possible."],["Center the patient","Fit and follow-up shape the workflow."]],status:"This foundation is ready for product renders, fitting protocols, bill-of-materials analysis, and partner validation.",next:"agentic-pollination-uav"},
  "agentic-pollination-uav": {
    number:"06", category:"Autonomous UAV", title:"Agentic Pollination UAV", accent:"#e4dff3",
    summary:"A full-stack autonomous pollinator-drone concept combining computer vision, mission planning, retrieval memory, simulation, and a physical UAV architecture.",
    tags:["TypeScript","FastAPI","Computer Vision","UAV"], repo:"https://github.com/zoraizmohammad/agentic-pollination-uav",
    problem:"Targeted pollination requires perception and motion to work together under changing field conditions. A useful system needs more than detection: it needs planning, mission memory, operator visibility, and a path to physical deployment.",
    approach:"A vision service identifies candidate targets, an agent plans actions using current observations and retrieved mission context, and a Preact dashboard exposes system state. Simulation provides a safe environment for testing the complete loop.",
    steps:["Field perception","Target identification","Agentic mission planning","UAV action + telemetry"],
    principles:[["Simulate the whole loop","Test planning, perception, and interface behavior as one system."],["Operator visibility","Expose targets, decisions, and mission state through a live dashboard."],["Memory-aware planning","Use prior mission context to inform what the agent does next."],["Hardware path","Keep the software architecture grounded in eventual onboard constraints."]],
    status:"The starter case study is ready for dashboard screenshots, detection examples, mission timelines, and an annotated drone-system diagram.", next:"ciphershield"
  },
  ctrlslash:{number:"07",category:"AI IDE Context",title:"CtrlSlash",accent:"#eadfbd",summary:"An MCP-based documentation and context engine that gives AI coding tools current, project-specific technical knowledge.",tags:["MCP","RAG","Puppeteer","Docker"],repo:"https://github.com/zoraizmohammad/ctrlslash",problem:"Coding agents often hallucinate when library documentation, repository conventions, and API behavior are absent or stale.",approach:"CtrlSlash collects documentation, indexes semantic context, and exposes retrieval through MCP at the point of implementation.",steps:["Collect sources","Normalize docs","Index context","Serve through MCP"],principles:[["Current sources","Refresh knowledge as dependencies evolve."],["Context on demand","Retrieve only what the task needs."],["Source visibility","Keep documentation links attached."],["IDE-native access","Deliver context inside the coding workflow."]],status:"The page is ready for ingestion traces, retrieval examples, and hallucination-reduction evaluation.",next:"ciphershield"},
  ciphershield: {
    number:"08", category:"Privacy Infrastructure", title:"CipherShield", accent:"#e4dff3",
    summary:"A privacy-preserving aggregation system that combines split-key homomorphic encryption with smart-contract verification for auditable protected-data computation.",
    tags:["OpenFHE","Solidity","C++","Cryptography"], repo:"https://github.com/zoraizmohammad/cipher-shield",
    problem:"Organizations may need aggregate insight from sensitive records without creating a central point where raw data can be exposed or misused. Policy alone cannot guarantee that separation.",
    approach:"Data remains encrypted during aggregation, while key responsibilities are split so that no single actor can decrypt inputs alone. Smart contracts provide a visible coordination and verification layer around the computation.",
    steps:["Encrypt at source","Aggregate ciphertexts","Verify on-chain","Jointly unlock result"],
    principles:[["Minimize trust","Replace promises about access with cryptographic constraints where possible."],["Aggregate, do not expose","Reveal the intended collective result without disclosing individual records."],["Split authority","Avoid concentrating decryption capability in a single participant."],["Auditable coordination","Use verifiable state transitions to make the protocol easier to inspect."]],
    status:"This page currently communicates the trust model at a high level. A later pass can include the threat model, protocol sequence, performance notes, and a formal explanation of the security assumptions.", next:"sonicsync"
  },
  sonicsync: {
    number:"09", category:"Human Sensing", title:"SonicSync", accent:"#dbe0e5",
    summary:"A submersible psychoacoustic feedback wearable developed with Garmin engineers for underwater communication and auditory testing across depth conditions.",
    tags:["MATLAB","C++","Hardware","IEEE"], repo:"https://github.com/zoraizmohammad/SonicSync",
    problem:"Sound perception and communication change underwater, while conventional laboratory equipment is poorly suited to mobile, depth-dependent testing. The apparatus needs to survive the environment without compromising timing or experimental control.",
    approach:"SonicSync joins a wearable mechanical enclosure with embedded signal processing, controlled stimulus delivery, and analysis tooling. The design connects physical fit, underwater constraints, and psychoacoustic measurement as one system.",
    steps:["Test protocol","Signal generation","Submersible wearable","Response analysis"],
    principles:[["Design for the environment","Treat pressure, water, fit, and usability as first-order system requirements."],["Low-latency feedback","Keep the sensing and stimulus loop responsive enough for controlled testing."],["Repeatable trials","Structure stimulus delivery and data capture for comparable sessions."],["Cross-disciplinary build","Unify mechanical, electrical, and analytical work in the same design process."]],
    status:"The starter page can grow with device photography, enclosure iterations, test setup diagrams, publication details, and measured results.", next:"revealgenomics"
  },
  revealgenomics: {
    number:"11", category:"Cancer Detection", title:"RevealGenomics", accent:"#f4d9d4",
    summary:"Exploratory breast-cancer gene detection research using representation learning and notebook-driven modeling to study BRCA-related classification signals.",
    tags:["Jupyter","VAE","Oncology","Representation Learning"], repo:"https://github.com/zoraizmohammad/RevealGenomics",
    problem:"High-dimensional gene-expression data contains complex structure, but small sample sizes and noisy signals make clinically meaningful patterns difficult to isolate and communicate.",
    approach:"The project explores learned latent representations as a way to compress expression features before downstream classification and analysis, with notebooks keeping preprocessing and experiments inspectable.",
    steps:["Expression data","Preprocess + normalize","Learn latent space","Explore classification signal"],
    principles:[["Explore before claiming","Use the work to surface patterns and hypotheses rather than overstate clinical readiness."],["Compact representation","Study whether latent variables capture useful structure in high-dimensional profiles."],["Visible experiments","Keep transformations and evaluation steps readable in notebooks."],["Biomedical context","Interpret modeling decisions through the constraints of oncology data."]],
    status:"This initial narrative is intentionally exploratory. It is ready for dataset documentation, latent-space plots, model comparisons, and limitations once the preferred experiments are chosen.", next:"lifeedit-gene-classifier"
  },
  "lifeedit-gene-classifier": {
    number:"10", category:"Genomics ML", title:"LifeEdit Gene Classifier", accent:"#dcefe5",
    summary:"A machine-learning workflow for distinguishing edited and unedited biological signatures using single-cell data, feature engineering, and exploratory modeling.",
    tags:["Python","Jupyter","Genomics","Classification"], repo:"https://github.com/zoraizmohammad/LifeEdit-geneclassifier",
    problem:"Gene-editing experiments can produce subtle expression changes across heterogeneous cell populations. Identifying a dependable signature requires careful preprocessing, dimensionality reduction, and evaluation—not only a classifier.",
    approach:"The workflow moves from exploratory analysis through feature selection and lower-dimensional representations to supervised classification, keeping each transformation available for biological review.",
    steps:["Single-cell inputs","Quality control + EDA","Feature selection + PCA","Edited / unedited model"],
    principles:[["Data quality first","Inspect distributions and artifacts before optimizing a model."],["Reduce with purpose","Use feature selection and PCA to clarify signal and manage dimensionality."],["Compare representations","Evaluate how preprocessing choices change downstream separability."],["Keep biology visible","Pair predictive results with interpretable features and careful limitations."]],
    status:"The page now provides a stable structure for the research story. Next additions can include cohort details, class balance, PCA views, evaluation metrics, and the most biologically informative features.", next:"fpga-hologram"
  },
  "fpga-hologram":{number:"12",category:"Digital Systems",title:"FPGA Hologram",accent:"#dbe8ed",summary:"A persistence-of-vision hologram display on a Nexys A7 FPGA with deterministic LED timing and a custom pipelined controller.",tags:["Verilog","VHDL","FPGA","Assembly"],repo:"https://github.com/zoraizmohammad/fpga-hologram",problem:"Stable volumetric imagery requires precise coordination between rotation, angular position, memory access, and LED updates.",approach:"A hardware pipeline maps angular position to texture ROM data while a custom controller handles timing and interaction.",steps:["Sense angle","Address texture","Pipeline pixels","Drive LEDs"],principles:[["Deterministic timing","Keep display updates cycle-accurate."],["Pipeline the path","Separate addressing, control, and output."],["Precompute assets","Use ROM layouts suited to hardware."],["Measure visually","Tune timing against perceived stability."]],status:"The page is ready for timing diagrams, RTL modules, hardware photography, and display captures.",next:"academicinsights"},
  academicinsights:{number:"13",category:"EdTech Research",title:"AcademicInsights",accent:"#dce2e0",summary:"A browser-based research system for studying learning behavior through web activity, language signals, and interpretable behavioral features.",tags:["Python","JavaScript","NLP","EdTech"],repo:"https://github.com/zoraizmohammad/academicInsights",problem:"Online learning behavior is distributed across browsing patterns and text interactions that are difficult to study without invasive collection.",approach:"The system combines a research-oriented browser extension with a backend analysis template for consent-aware behavioral and NLP experiments.",steps:["Collect consented events","Extract features","Analyze behavior","Review findings"],principles:[["Research consent","Make collection explicit and bounded."],["Minimize data","Capture only signals required by the study."],["Interpretable features","Prefer measures researchers can inspect."],["Separate observation","Keep collection and analysis modular."]],status:"The page is ready for study protocols, privacy controls, feature definitions, and research outputs.",next:"provenia-bio"
  }
};

const slug = document.body.dataset.project;
const project = projects[slug];
if (!project) throw new Error(`Unknown project: ${slug}`);

document.body.style.setProperty("--project-accent", project.accent);
document.title = `${project.title} | Mohammad Zoraiz`;

const nodes = project.steps.map((step,index) => `<div class="system-node"><span>0${index + 1}</span><strong>${step}</strong></div>`).join("");
const notes = project.principles.map(([title,copy],index) => `<article class="case-note"><span>Principle 0${index + 1}</span><h3>${title}</h3><p>${copy}</p></article>`).join("");
const tags = project.tags.map(tag => `<span>${tag}</span>`).join("");
const next = projects[project.next];
const systemVisual = slug === "agentic-pollination-uav" ? `<figure class="uav-system"><img src="../assets/projects/agentic-pollination-uav/figures/system-overview.svg" alt="UAV hardware, perception, decision, and pollination architecture"><figcaption>Sensor and camera inputs feed perception; bounded reasoning produces deterministic action commands.</figcaption></figure>` : `<div class="system-map" style="--steps:${project.steps.length}">${nodes}</div>`;

const ombenchPage = `
  <section class="project-cover ombench-cover" id="first-content"><div class="case-hero research-cover-grid">
    <div class="blog-intro"><div class="case-kicker"><a class="project-back" href="../projects.html">← All projects</a><span class="case-number">04 / Agent Memory</span></div><h1 class="case-title">Ombench</h1><p class="case-summary">A causal evaluation substrate for compiling operational memory and measuring whether it improves agents under identical historical conditions.</p><p class="research-byline">Mohammad Zoraiz · Open-source research system</p><div class="case-actions"><a class="button button-primary" href="${project.repo}" target="_blank" rel="noreferrer">Code <span>↗</span></a><a class="button button-quiet" href="#protocol">Protocol <span>↓</span></a><a class="button button-quiet" href="../assets/projects/ombench/demo/backtest.html" target="_blank">Dashboard <span>↗</span></a></div><div class="case-tags">${tags}</div></div>
    <figure class="research-cover-media abstract-cover"><img src="../assets/projects/covers/ombench.png" alt="Abstract geometric memory topology poster for Ombench"><figcaption>Capture · compile · replay · measure</figcaption></figure>
  </div></section>
  <nav class="research-toc" aria-label="On this page"><a href="#premise">Premise</a><a href="#architecture">Architecture</a><a href="#history">History</a><a href="#memory">Memory</a><a href="#protocol">Backtest</a><a href="#results">Results</a><a href="#limits">Limits</a></nav>
  <section class="research-metrics" aria-label="Ombench benchmark results"><div><strong>15</strong><span>curated operational tasks</span></div><div><strong>+0.622</strong><span>mean outcome-score delta</span></div><div><strong>14 / 15</strong><span>tasks improve · zero regress</span></div><div><strong>p = 0.00018</strong><span>paired Wilcoxon · SciPy</span></div></section>

  <article class="research-prose" id="premise"><p class="section-index">01 / Evaluation premise</p><h2>Memory is a treatment, not a feature demo</h2><p>Operational agents repeatedly encounter preferences, prior decisions, approval chains, and application-specific norms. Storing that context is easy; demonstrating that it caused a better action is harder. Ombench converts past work into replayable history, compiles durable knowledge, and evaluates the same agent twice against the same frozen state.</p><div class="research-callout"><span>Causal contrast</span><p>Task, application snapshot, clock, sandbox, rubric, and agent policy are held fixed. The intervention is whether the compiled knowledge base is mounted.</p></div></article>

  <figure class="research-figure ombench-diagram" id="architecture"><div class="diagram-viewport"><object data="../assets/projects/ombench/diagrams/architecture.svg" type="image/svg+xml" aria-label="Original Ombench capture, history, compilation, replay, and measurement architecture"></object></div><figcaption><strong>End-to-end architecture.</strong> Original repository diagram: agent trajectories and SaaS state converge in an append-only history substrate, then branch into snapshot replay and memory retrieval for paired evaluation.</figcaption></figure>

  <section class="research-wide research-section"><p class="section-index">02 / Layered system</p><h2>A history engine beneath the agent</h2><div class="research-comparison"><article><span>Capture</span><h3>Agent-agnostic traces</h3><p>Claude Code and Codex transcripts normalize into one OpenTelemetry-aligned span model. Redaction precedes persistence and large payloads move to a content-addressed blob store.</p></article><article><span>Integrate</span><h3>Canonical app events</h3><p>Slack, Calendar, Docs, and Gmail fixtures and live connectors map heterogeneous APIs into one event algebra.</p></article><article><span>Compile</span><h3>Auditable memory files</h3><p>Episodic, semantic, and procedural memories remain readable Markdown with YAML metadata, provenance, confidence, TTL, and ACL.</p></article><article><span>Evaluate</span><h3>Deterministic replay</h3><p>A frozen clock and seeded snapshot isolate the effect of retrieval from changes in external state.</p></article></div></section>
  <figure class="research-figure ombench-diagram"><div class="diagram-viewport"><object data="../assets/projects/ombench/diagrams/layers.svg" type="image/svg+xml" aria-label="Original Ombench package dependency layers"></object></div><figcaption><strong>Dependency discipline.</strong> Higher-level CLI, evaluation, memory, and integration packages depend strictly downward on the shared trace, event, and storage substrate.</figcaption></figure>

  <article class="research-prose" id="history"><p class="section-index">03 / Bitemporal state</p><h2>Reconstruct what was true—and what was knowable</h2><p>Every application event carries valid time <span class="inline-equation">T</span>, when the source change took effect, and transaction time <span class="inline-equation">τ</span>, when Ombench learned it. Historical state is a deterministic fold:</p><div class="equation-block">S(T,τ) = fold(S₀, {e | valid_at(e) ≤ T ∧ ingested_at(e) ≤ τ})</div><p>The second axis prevents late-arriving backfills from leaking information into an earlier replay. Canonical JSON payloads are addressed by SHA-256; snapshot manifests form Merkle-style roots over entity-version hashes.</p></article>
  <figure class="research-figure ombench-diagram"><div class="diagram-viewport"><object data="../assets/projects/ombench/diagrams/bitemporal.svg" type="image/svg+xml" aria-label="Original Ombench bitemporal event and snapshot diagram"></object></div><figcaption><strong>Bitemporal reconstruction.</strong> Valid time and ingestion time jointly bound the evidence available to an agent at any replay coordinate.</figcaption></figure>

  <article class="research-prose" id="memory"><p class="section-index">04 / Memory compiler</p><h2>Durable knowledge with explicit provenance</h2><p>Candidate memories are extracted from trajectories and application state, assigned evidence-based logistic confidence, promoted above the configured threshold, deduplicated by content hash, and stored append-only. Contradictions create <code>supersedes</code> and <code>contradicts</code> edges instead of rewriting history.</p><div class="equation-block">P(promote | z) = σ(β₀ + βᵀz)</div><h3>Hybrid retrieval under a token budget</h3><p>Queries route to likely namespaces. BM25 and dense ranks are fused with reciprocal-rank fusion, expanded one hop over provenance edges, and reranked by confidence, freshness, namespace prior, contradiction risk, and privacy risk:</p><div class="equation-block">RRF(d) = Σ<sub>r∈{lex,dense}</sub> 1 / (k + rank<sub>r</sub>(d))</div><p>A final value-per-token packer favors compact, high-utility context over indiscriminate history dumping.</p></article>

  <section class="research-wide research-section" id="protocol"><p class="section-index">05 / Paired backtest</p><h2>One snapshot, two conditions</h2><p class="research-lede">Each task declares a prompt, bitemporal coordinates, expected memory, and state-based rubric. Ombench materializes the snapshot once, seeds identical sandboxes, runs without and with memory, and computes a paired outcome-grounded delta.</p><div class="rubric-grid"><article><span>01</span><h3>Outcome</h3><p>Did the task reach the expected end state?</p></article><article><span>02</span><h3>Retrieval</h3><p>Was the expected memory retrieved precisely?</p></article><article><span>03</span><h3>Application</h3><p>Did the action actually reflect that memory?</p></article><article><span>04</span><h3>Validity</h3><p>Were writes in-scope and side effects safe?</p></article></div><p class="research-lede">The headline uses outcome and action validity only. Memory retrieval and application are diagnostic axes because they are zero by construction in the no-memory condition.</p></section>
  <figure class="research-figure ombench-diagram"><div class="diagram-viewport"><object data="../assets/projects/ombench/diagrams/backtest.svg" type="image/svg+xml" aria-label="Original paired Ombench backtest protocol"></object></div><figcaption><strong>Paired intervention.</strong> Both branches begin from the same task specification and reconstructed snapshot; only the mounted memory differs.</figcaption></figure>

  <section class="research-wide research-section" id="results"><p class="section-index">06 / Deterministic benchmark</p><h2>Memory improves fourteen tasks and regresses none</h2><p class="research-lede">The checked-in keyless run evaluates fifteen curated operational tasks spanning scheduling, announcements, document conventions, approvals, contacts, travel, time zones, summaries, routing, communication norms, project updates, triage, and failure recovery.</p><div class="result-table-wrap"><table class="result-table"><thead><tr><th>Metric</th><th>Without memory</th><th>With memory</th><th>Paired change</th></tr></thead><tbody><tr><td>Mean outcome-grounded score</td><td>0.3777</td><td>1.0000</td><td>+0.6223 · 95% CI [0.5334, 0.6667]</td></tr><tr><td>Success rate</td><td>6.67%</td><td>100%</td><td>+93.33 percentage points</td></tr><tr><td>Win rate</td><td>—</td><td>0.9333</td><td>95% CI [0.8, 1.0]</td></tr><tr><td>Paired significance</td><td colspan="2">14 positive · 1 neutral · 0 negative</td><td>Wilcoxon p = 0.0001828</td></tr></tbody></table></div><div class="qbl-result-callouts"><article><strong>407</strong><span>repository-reported keyless tests</span></article><article><strong>91%</strong><span>repository-reported core substrate coverage</span></article><article><strong>0</strong><span>credentials required for deterministic demo</span></article></div><p class="caption">Test and coverage counts are repository-reported; this portfolio pass did not recreate the absent local environment.</p></section>

  <article class="research-prose"><p class="section-index">07 / Concrete intervention</p><h2>“Reschedule my 1:1 with Bob.”</h2><p>The calendar snapshot contains the event but not the durable preference that the user favors afternoons and avoids Fridays. Without memory, the deterministic agent selects noon and fails the rubric. With the provenance-linked preference mounted, it chooses 3 p.m.; outcome, retrieval, application, and validity all score correctly.</p><div class="research-callout"><span>Why this task counts</span><p>The correct action cannot be inferred reliably from current application state alone. Its decisive evidence exists only in prior interaction history.</p></div></article>

  <article class="research-prose" id="limits"><p class="section-index">08 / Scope &amp; limitations</p><h2>A measurement substrate, not universal memory proof</h2><ul class="research-limitations"><li><strong>Curated synthetic suite.</strong> The headline run uses fifteen deterministic fixture-backed tasks, not uncontrolled production traffic.</li><li><strong>Stub-agent ceiling.</strong> The with-memory condition reaches 1.0 by construction of a deterministic agent and explicit expected memories; live-model variance needs repeated trials.</li><li><strong>Memory ablation.</strong> This study isolates mounted versus absent memory, not every retriever, compiler, TTL, or ranking component independently.</li><li><strong>Judge boundary.</strong> The keyless result uses rule-based state validators. An optional blind Anthropic judge refines only the application axis.</li><li><strong>Operational privacy.</strong> ACLs, redaction, contradiction handling, and forgetting policies are implemented, but production deployment still requires organization-specific governance.</li></ul></article>
  <section class="research-wide research-section reproducibility-block"><p class="section-index">09 / Reproducibility</p><h2>Replay the entire intervention without credentials</h2><p class="research-lede"><code>make demo</code> synchronizes bundled fixtures, seeds memory, runs both conditions across all fifteen tasks, and produces the report represented here.</p><div class="case-actions"><a class="button button-primary" href="${project.repo}" target="_blank" rel="noreferrer">Open repository <span>↗</span></a><a class="button button-quiet" href="../assets/projects/ombench/data/benchmark-output.txt">Benchmark output <span>↓</span></a><a class="button button-quiet" href="../assets/projects/ombench/demo/backtest.html" target="_blank">Open dashboard <span>↗</span></a></div></section>
  <a class="case-next" href="qadam.html"><span>Next project / 05</span><strong>Qadam →</strong></a>`;

const quantumBayesianPage = `
  <section class="project-cover qbl-cover" id="first-content"><div class="case-hero research-cover-grid">
    <div class="blog-intro"><div class="case-kicker"><a class="project-back" href="../projects.html">← All projects</a><span class="case-number">03 / Quantum Systems</span></div>
    <h1 class="case-title"><span>Quantum</span> <span>Bayesian</span><span>Learner</span></h1><p class="case-summary">Hardware-aware structured compression for quantum belief models under real post-transpile circuit cost.</p>
    <p class="research-byline">Mohammad Zoraiz · Duke University · Pratt School of Engineering</p>
    <div class="venue-badge"><span>Accepted</span> IEEE Quantum Week QCE26 · Poster Track · Submission 1846</div>
    <div class="case-actions"><a class="button button-primary" href="../assets/projects/quantum-bayesian-learner/documents/qce26-poster.pdf" target="_blank" rel="noreferrer">Poster <span>↗</span></a><a class="button button-quiet" href="${project.repo}" target="_blank" rel="noreferrer">Code <span>↗</span></a><a class="button button-quiet" href="#method">Method <span>↓</span></a></div><div class="case-tags">${tags}</div></div>
    <figure class="research-cover-media abstract-cover"><img src="../assets/projects/covers/quantum-bayesian-learner.png" alt="Abstract quantum interaction field poster"><figcaption>Belief · structure · hardware</figcaption></figure>
  </div></section>
  <nav class="research-toc" aria-label="On this page"><a href="#premise">Premise</a><a href="#method">Method</a><a href="#frontier">Frontier</a><a href="#structure">Structure</a><a href="#hardware">Hardware</a><a href="#poster">Poster</a><a href="#limits">Limits</a></nav>
  <section class="research-metrics" aria-label="Key experimental results"><div><strong>12 → 3</strong><span>maskable terms retained at hard-task optimum</span></div><div><strong>49 / 55</strong><span>paired wins over random masks</span></div><div><strong>p = 1.7×10⁻⁸</strong><span>one-sided Wilcoxon signed-rank</span></div><div><strong>0.83</strong><span>compressed accuracy on ibm_fez · n=40</span></div></section>

  <article class="research-prose" id="premise"><p class="section-index">01 / Research question</p><h2>How much entanglement does the task actually need?</h2><p>Quantum Bayesian models represent belief through quantum state and channel dynamics, but near-term hardware turns every two-qubit interaction into a reliability cost. This work asks where representational capacity ends and redundant entangling structure begins.</p><div class="research-callout"><span>Central contribution</span><p>The optimization target uses the number of two-qubit gates after deterministic transpilation to IBM FakeManila—including routing overhead—not an abstract pre-transpile gate count.</p></div></article>

  <figure class="research-figure qbl-source-figure" id="method"><img src="../assets/projects/quantum-bayesian-learner/figures/learner-pipeline.png" alt="Original quantum Bayesian learner pipeline showing stimulus encoding, evidence channel, masked Heisenberg ansatz, measurement, and hardware cost"><figcaption><strong>Quantum Bayesian learner.</strong> The original repository diagram traces feature evidence through a masked two-qubit variational circuit and single-qubit Pauli readout, while transpilation exposes the deployable two-qubit cost.</figcaption></figure>

  <article class="research-prose"><p class="section-index">02 / Belief update</p><h2>Two realizations of the same computational hypothesis</h2><p>The fast experimental engine evolves a two-qubit pure state from <span class="inline-equation">|00⟩</span>. A literal density-matrix realization begins with the maximally mixed prior <span class="inline-equation">ρ₀ = I / 2ⁿ</span> and applies a stimulus-conditioned Lüders filter:</p><div class="equation-block">ρ′(x) = K<sub>x</sub> ρ K<sub>x</sub><sup>†</sup> / Tr[K<sub>x</sub> ρ K<sub>x</sub><sup>†</sup>]</div><p>The non-unital update allows evidence to move a maximally mixed belief state; amplitude damping adds a multi-Kraus channel. The density model is Hermitian, positive semidefinite, trace-one, and reproduces the qualitative compression result across three seeds.</p><h3>Re-uploaded variational evidence</h3><p>Each of four layers encodes the two-feature stimulus with <span class="inline-equation">R<sub>Y</sub>(πx)R<sub>Z</sub>(πx)</span>, applies trainable single-qubit rotations, then masked Heisenberg interactions:</p><div class="equation-block">U<sub>H</sub>(θ,m) = ∏<sub>P∈{X,Y,Z}</sub> R<sub>PP</sub>(m<sub>ℓ,P</sub> θ<sub>ℓ,P</sub>)</div><p>The runtime binary mask contains twelve terms—three interaction axes over four layers. A trainable linear head maps <span class="inline-equation">⟨Z₀⟩, ⟨Z₁⟩, ⟨X₀⟩, ⟨X₁⟩</span> to a Bernoulli prediction.</p></article>

  <section class="research-wide research-section"><p class="section-index">03 / Structured compression</p><h2>Optimize the circuit the backend will execute</h2><div class="research-comparison"><article><span>Cost</span><h3>Post-transpile N₂q</h3><p>Qiskit transpiles each discrete mask to the five-qubit FakeManila coupling map at optimization level 1 with seed 42. Inserted SWAPs remain in the cost.</p></article><article><span>Search</span><h3>Greedy trajectory</h3><p>At each budget, the interaction whose removal least increases training cross-entropy is dropped, followed by warm-start retraining.</p></article><article><span>Operating point</span><h3>Regularized selection</h3><p>Each λ selects the recorded trajectory point minimizing cross-entropy plus hardware cost.</p><div class="mini-equation">L<sub>λ</sub>(m,θ)=CE(m,θ)+λN<sub>2q</sub>(m)</div></article><article><span>Control</span><h3>Matched random masks</h3><p>Random circuits are trained at identical active-term and two-qubit budgets, isolating topology from gate count.</p></article></div></section>

  <figure class="research-figure qbl-source-figure"><img src="../assets/projects/quantum-bayesian-learner/figures/checkerboards.png" alt="Easy, medium, and hard checkerboard categorization tasks"><figcaption><strong>Controlled task family.</strong> Checkerboard frequency 2, 3, and 4 defines easy, medium, and hard two-feature categorization without changing sample count or class balance.</figcaption></figure>

  <section class="research-wide research-section" id="frontier"><p class="section-index">04 / Capacity frontier</p><h2>Entanglement has a sharp lower boundary</h2><p class="research-lede">Across five seeds, removing every entangler collapses easy and hard tasks to chance and reduces medium accuracy to 0.643. Yet one to three retained terms recover most capacity. The hard-task mean reaches 0.927 at six two-qubit gates versus 0.873 at the full 24-gate cost; that difference is not statistically significant at five seeds.</p><div class="result-table-wrap"><table class="result-table"><thead><tr><th>Difficulty</th><th>N₂q = 0</th><th>Best compressed</th><th>Full · N₂q = 24</th></tr></thead><tbody><tr><td>Easy · frequency 2</td><td>0.523 ± 0.032</td><td>0.970 ± 0.032 · N₂q=4</td><td>0.940 ± 0.025</td></tr><tr><td>Medium · frequency 3</td><td>0.643 ± 0.093</td><td>0.973 ± 0.019 · N₂q=2</td><td>0.947 ± 0.022</td></tr><tr><td>Hard · frequency 4</td><td>0.493 ± 0.096</td><td>0.927 ± 0.042 · N₂q=6</td><td>0.873 ± 0.073</td></tr></tbody></table></div></section>
  <figure class="research-figure qbl-source-figure"><img src="../assets/projects/quantum-bayesian-learner/figures/frontier-family.png" alt="Five-seed test accuracy versus FakeManila post-transpile two-qubit gate count"><figcaption><strong>Accuracy–complexity frontier.</strong> Mean ± standard deviation over five seeds. A broad plateau separates the necessary first interaction from redundant full-circuit capacity.</figcaption></figure>

  <section class="research-wide research-section" id="structure"><p class="section-index">05 / Matched-budget ablation</p><h2>Which interactions survive matters more than how many</h2><p class="research-lede">On the hard task, greedy masks outperform connectivity-matched random masks at every reported budget. Across 55 paired seed–budget comparisons, the learned structure wins 49, with mean advantage +0.083 and one-sided Wilcoxon <span class="inline-equation">p ≈ 1.7 × 10⁻⁸</span>.</p><div class="qbl-result-callouts"><article><strong>+0.119</strong><span>largest mean advantage · N₂q=10</span></article><article><strong>+0.112</strong><span>advantage at the six-gate operating point</span></article><article><strong>11 / 11</strong><span>budgets favor learned topology on average</span></article></div></section>
  <figure class="research-figure qbl-source-figure"><img src="../assets/projects/quantum-bayesian-learner/figures/mask-ablation.png" alt="Learned versus matched random mask accuracy on the hard task"><figcaption><strong>Structure ablation.</strong> Learned and random masks have the same deployed gate budget; the significant test is paired across seeds and budgets, while plotted bars show unpaired dispersion.</figcaption></figure>

  <section class="research-wide research-section" id="hardware"><p class="section-index">06 / Physical quantum hardware</p><h2>The frontier reverses on IBM Heron hardware</h2><p class="research-lede">The same trained parameters were executed on the 156-qubit <code>ibm_fez</code> backend. In the 16-point frontier run at 2,048 shots, accuracy holds at 0.8125 for N₂q=2 and 6, falls to 0.75 at 12, and reaches 0.5625 at 18 and 24. A separate 40-point, 4,096-shot endpoint run measures 0.83 for the compressed circuit and 0.60 for the full circuit.</p><div class="research-callout"><span>Hardware provenance</span><p>Physical-device results use one training seed, primitive-default mitigation, optimization level 1, and transpiler seed 42. FakeManila defines the controlled cost proxy; ibm_fez is the deployment device.</p></div></section>
  <div class="research-gallery qbl-gallery"><figure><img src="../assets/projects/quantum-bayesian-learner/figures/hardware-frontier.png" alt="Exact and ibm_fez accuracy across five gate budgets"><figcaption>Single-seed device frontier · 16 stimuli · 2,048 shots.</figcaption></figure><figure><img src="../assets/projects/quantum-bayesian-learner/figures/hardware-real.png" alt="Full versus compressed circuit accuracy on ibm_fez"><figcaption>Endpoint confirmation · 40 stimuli · 4,096 shots.</figcaption></figure><figure><img src="../assets/projects/quantum-bayesian-learner/figures/noise-robustness.png" alt="Exact and FakeManila noise-model robustness"><figcaption>Five-seed Aer noise-model robustness.</figcaption></figure><figure><img src="../assets/projects/quantum-bayesian-learner/figures/density-frontier.png" alt="Density-matrix model accuracy complexity frontier"><figcaption>Literal mixed-state confirmation · three seeds.</figcaption></figure></div>

  <section class="research-wide research-section" id="poster"><p class="section-index">07 / IEEE Quantum Week</p><h2>Accepted to QCE26 · Poster Track</h2><p class="research-lede">The accepted poster packages the motivation, exact quantum learner, post-transpile cost, structured pruning, robustness studies, physical-device run, and calibrated limitations into one research artifact.</p><div class="case-actions"><a class="button button-primary" href="../assets/projects/quantum-bayesian-learner/documents/qce26-poster.pdf" target="_blank" rel="noreferrer">View full poster <span>↗</span></a><a class="button button-quiet" href="../assets/projects/quantum-bayesian-learner/documents/extended-abstract.pdf" target="_blank" rel="noreferrer">Extended abstract <span>↗</span></a><a class="button button-quiet" href="../assets/projects/quantum-bayesian-learner/documents/paper.pdf" target="_blank" rel="noreferrer">Read paper <span>↗</span></a></div></section>
  <figure class="research-figure poster-figure qbl-poster"><a href="../assets/projects/quantum-bayesian-learner/documents/qce26-poster.pdf" target="_blank" rel="noreferrer"><img src="../assets/projects/quantum-bayesian-learner/figures/qce26-poster.png" alt="Accepted IEEE Quantum Week QCE26 poster for hardware-aware quantum Bayesian learner compression"></a><figcaption><strong>QCE26 accepted poster.</strong> Hardware-Aware Quantum Bayesian Learner Compression: Linking Human Belief Updating to NISQ Circuit Complexity.</figcaption></figure>

  <article class="research-prose" id="limits"><p class="section-index">08 / Scope &amp; limitations</p><h2>A controlled capacity study—not a claim of quantum advantage</h2><ul class="research-limitations"><li><strong>Small system.</strong> The primary learner uses two qubits and synthetic two-feature categorization tasks.</li><li><strong>Limited hardware sample.</strong> Device evidence is single-seed with 16-point frontier and 40-point endpoint evaluations; job IDs were not retained.</li><li><strong>No explicit mitigation.</strong> Hardware runs use primitive defaults without configured error-mitigation strategies.</li><li><strong>Cost-device mismatch.</strong> FakeManila supplies the reproducible transpilation cost while ibm_fez supplies physical measurements.</li><li><strong>No quantum advantage claim.</strong> RBF-SVM and MLP baselines remain strong; the contribution is hardware-aware capacity characterization.</li><li><strong>Density confirmation.</strong> The literal mixed-state realization uses three seeds rather than the five used in the primary study.</li></ul></article>
  <section class="research-wide research-section reproducibility-block"><p class="section-index">09 / Reproducibility</p><h2>Every figure resolves to logged runs</h2><p class="research-lede">The repository includes exact JAX/Qiskit verification, deterministic transpilation, per-seed CSVs, IBM hardware logs, figure-generation scripts, paper source, and the complete submission package.</p><div class="case-actions"><a class="button button-primary" href="${project.repo}" target="_blank" rel="noreferrer">Open repository <span>↗</span></a><a class="button button-quiet" href="../assets/projects/quantum-bayesian-learner/data/hard-frontier.csv">Frontier CSV <span>↓</span></a><a class="button button-quiet" href="../assets/projects/quantum-bayesian-learner/data/ibm-fez-frontier.json">Hardware JSON <span>↓</span></a></div></section>
  <a class="case-next" href="ombench.html"><span>Next project / 04</span><strong>Ombench →</strong></a>`;

const targetOncoPage = `
  <section class="project-cover targetonco-cover" id="first-content"><div class="case-hero research-cover-grid">
    <div class="blog-intro"><div class="case-kicker"><a class="project-back" href="../projects.html">← All projects</a><span class="case-number">02 / Precision Oncology</span></div>
    <h1 class="case-title">TargetONCO</h1><p class="case-summary">A traceable multimodal workspace for radiology reasoning, spatial-proteomics quantification, and phenotype-aware cohort retrieval.</p>
    <p class="research-byline">Mohammad Zoraiz · YuCheng (Tom) Yuan · Sheldon Lewis · Suhas Kurapati</p>
    <div class="case-actions"><a class="button button-primary" href="${project.repo}" target="_blank" rel="noreferrer">Code <span>↗</span></a><a class="button button-quiet" href="#architecture">Architecture <span>↓</span></a></div><div class="case-tags">${tags}</div></div>
    <figure class="research-cover-media abstract-cover"><img src="../assets/projects/covers/targetonco.png" alt="Abstract geometric cellular atlas poster for TargetONCO"><figcaption>Radiology · spatial biology · retrieval</figcaption></figure>
  </div></section>
  <nav class="research-toc" aria-label="On this page"><a href="#overview">Overview</a><a href="#architecture">Architecture</a><a href="#radiology">OncoRAX</a><a href="#pathology">Spatial</a><a href="#results">Evidence</a><a href="#limitations">Limits</a></nav>
  <section class="research-metrics" aria-label="System dimensions"><div><strong>3</strong><span>specialist analysis systems</span></div><div><strong>70D</strong><span>tissue phenotype vector</span></div><div><strong>10D</strong><span>single-cell marker vector</span></div><div><strong>7</strong><span>traceable report stages</span></div></section>

  <article class="research-prose" id="overview"><p class="section-index">01 / Research premise</p><h2>Different evidence should remain different</h2><p>Precision-oncology workflows span images, cellular phenotypes, clinical context, and narrative interpretation. TargetONCO does not collapse those signals into one opaque prediction. It routes each modality through a specialist pipeline, preserves intermediate artifacts, and reunifies the outputs as evidence for human review.</p><div class="research-callout"><span>Evidence boundary</span><p>This is a research prototype and decision-support demonstration—not a clinically validated diagnostic device. Architectural dimensions and checked-in execution traces are reported separately from clinical performance.</p></div></article>

  <figure class="research-figure target-reference-diagram" id="architecture"><img src="../assets/projects/targetonco/figures/system-simplified.png" alt="Original TargetONCO system diagram connecting the frontend to X-ray analysis, OncoRAX reporting, OME-TIFF pathology, cell annotation, and Elasticsearch retrieval"><figcaption><strong>Multimodal architecture.</strong> The original project diagram shows the two primary paths from the frontend: radiology through OncoRAX and spatial pathology through OncoPathology, cell annotation, quantification, and retrieval.</figcaption></figure>

  <section class="research-wide research-section"><p class="section-index">02 / Computational contract</p><h2>Specialists first; synthesis second</h2><div class="research-comparison"><article><span>Radiology</span><h3>OncoRAX</h3><p>A staged inference, critique, analogous-case retrieval, revision, differential-ranking, and reporting loop retains a timestamped event trace.</p></article><article><span>Spatial pathology</span><h3>OncoPathology</h3><p>Probability maps, cell segmentation, and marker quantification convert multi-channel OME-TIFF imagery into analysis-ready single-cell tables.</p></article><article><span>Cohort intelligence</span><h3>Elasticsearch</h3><p>Normalized marker summaries become dense tissue and cell embeddings with attached morphology and clinical metadata.</p></article><article><span>Orchestration</span><h3>FastAPI + React</h3><p>A typed web interface coordinates long-running local, containerized, Modal, or HPC execution while preserving generated artifacts.</p></article></div></section>

  <figure class="research-figure target-reference-diagram target-reference-diagram-complex" id="radiology"><img src="../assets/projects/targetonco/figures/system-complex.png" alt="Original detailed TargetONCO architecture diagram showing frontend, agent core, OncoRAX, OncoPathology, vector search, execution backends, and reporting outputs"><figcaption><strong>Complete implementation topology.</strong> The repository’s detailed reference diagram maps the frontend and agent core to OncoRAX, OncoPathology, vector search, execution backends, data stores, and research-report outputs.</figcaption></figure>

  <article class="research-prose"><p class="section-index">03 / Probabilistic reasoning</p><h2>Ranking hypotheses without hiding uncertainty</h2><p>The radiology path represents candidate findings with confidence scores, retrieves analogous cases, and forms a normalized differential. Its Bayesian stage can be written as:</p><div class="equation-block">P(D<sub>i</sub> | F) = P(F | D<sub>i</sub>) P(D<sub>i</sub>) / Σ<sub>j</sub> P(F | D<sub>j</sub>) P(D<sub>j</sub>)</div><p>Here, <span class="inline-equation">F</span> denotes the observed finding set and <span class="inline-equation">Dᵢ</span> a candidate diagnosis. OncoRAX stores the inference, critique, retrieved cases, revision, differential, and report as separate timeline events so a reviewer can inspect where a conclusion changed.</p></article>

  <section class="research-wide research-section" id="pathology"><p class="section-index">04 / Spatial proteomics</p><h2>From multiplex pixels to cellular phenotypes</h2><div class="oncology-flow"><article><span>01</span><h3>UnMicst</h3><p>Produces probability maps from raw multi-channel OME-TIFF tissue imagery.</p></article><article><span>02</span><h3>S3segmenter</h3><p>Resolves nuclei and cell boundaries into spatially indexed masks.</p></article><article><span>03</span><h3>mcquant</h3><p>Quantifies per-cell marker intensity and morphology into tabular output.</p></article></div><p class="research-lede">The execution layer detects Docker, Apptainer/Singularity, Modal, or local runtimes, making multi-gigabyte jobs portable across workstation and HPC environments.</p></section>

  <article class="research-prose"><p class="section-index">05 / Phenotype retrieval</p><h2>A common vocabulary across cohorts</h2><p>Ten shared markers—CD31, CD45, CD4, FOXP3, CD8, CD163, E-cadherin, SMA, pan-cytokeratin, and CD3—align Orion-CRC and OncoPathology outputs. Intensities are transformed and standardized per marker:</p><div class="equation-block">z<sub>m,c</sub> = [asinh(x<sub>m,c</sub> / 5) − μ<sub>m</sub>] / σ<sub>m</sub></div><p>Each cell is represented by ten normalized marker values. A tissue vector concatenates seven distribution summaries—mean, standard deviation, and the 10th, 25th, 50th, 75th, and 90th percentiles—for every marker, yielding <span class="inline-equation">10 × 7 = 70</span> dimensions. Elasticsearch ranks cosine-nearest phenotypes:</p><div class="equation-block">sim(q, x) = (q · x) / (‖q‖₂ ‖x‖₂)</div></article>

  <section class="research-wide research-section" id="results"><p class="section-index">06 / Checked-in evidence</p><h2>One trace, reported as one trace</h2><p class="research-lede">The repository includes functional tests across normal, pneumonia, and cancer examples. The measurements below come from the checked-in <code>cancer4</code> demonstration and characterize execution behavior—not diagnostic accuracy.</p><div class="result-table-wrap"><table class="result-table"><thead><tr><th>Observed artifact</th><th>Demo value</th><th>What it establishes</th></tr></thead><tbody><tr><td>Initialization → final report</td><td>17.6 s</td><td>A complete seven-stage trace was emitted.</td></tr><tr><td>Extracted findings</td><td>8 total · 5 unique</td><td>Findings and confidence metadata were serialized.</td></tr><tr><td>Analogous cases</td><td>5 retrieved</td><td>Retrieval context was attached before revision.</td></tr><tr><td>Differential hypotheses</td><td>8 ranked</td><td>Probabilities were normalized into a reviewable table.</td></tr><tr><td>Visual outputs</td><td>5 generated</td><td>Image annotation and summary plots were exported.</td></tr></tbody></table></div></section>
  <div class="research-gallery oncology-gallery"><figure><img src="../assets/projects/targetonco/figures/annotated_xray_cancer4.png" alt="Annotated demonstration chest radiograph"><figcaption>Model findings overlaid on the demonstration radiograph.</figcaption></figure><figure><img src="../assets/projects/targetonco/figures/differential_chart_cancer4.png" alt="Ranked differential diagnosis chart"><figcaption>Normalized differential emitted by the example trace.</figcaption></figure><figure><img src="../assets/projects/targetonco/figures/regional_heatmap_cancer4.png" alt="Regional finding heatmap"><figcaption>Regional distribution of extracted findings.</figcaption></figure><figure><img src="../assets/projects/targetonco/figures/finding_stats_cancer4.png" alt="Finding confidence statistics"><figcaption>Finding frequency and confidence summary.</figcaption></figure></div>

  <article class="research-prose" id="limitations"><p class="section-index">07 / Limitations</p><h2>Useful infrastructure; open clinical questions</h2><ul class="research-limitations"><li><strong>No clinical validation.</strong> The checked-in examples demonstrate software execution and report structure, not sensitivity, specificity, calibration, or patient benefit.</li><li><strong>Single-trace timing.</strong> The 17.6-second figure is derived from one serialized demo timeline and is not a controlled latency benchmark.</li><li><strong>Model failure is visible.</strong> In the selected trace, the dedicated report-generation tool fails on a missing configuration field; classifier output provides the fallback evidence.</li><li><strong>Retrieval configuration matters.</strong> Elasticsearch can fall back to fixtures, and cohort similarity is exploratory unless dataset provenance and outcome labels are validated.</li><li><strong>Human review is mandatory.</strong> Generated differentials and summaries must not be interpreted as medical advice or autonomous diagnosis.</li></ul></article>
  <section class="research-wide research-section reproducibility-block"><p class="section-index">08 / Reproducibility</p><h2>Inspect the implementation and trace</h2><p class="research-lede">The repository contains the orchestration code, preprocessing equations, container recipes, test documentation, and serialized intermediate results used to construct this case study.</p><div class="case-actions"><a class="button button-primary" href="${project.repo}" target="_blank" rel="noreferrer">Open repository <span>↗</span></a><a class="button button-quiet" href="../assets/projects/targetonco/data/demo-trace.json">Demo trace <span>↓</span></a></div></section>
  <a class="case-next" href="quantum-bayesian-learner.html"><span>Next project / 03</span><strong>Quantum Bayesian Learner →</strong></a>`;

const uavPage = `
  <section class="project-cover pollinator-cover" id="first-content"><div class="case-hero research-cover-grid">
    <div class="blog-intro"><div class="case-kicker"><a class="project-back" href="../projects.html">← All projects</a><span class="case-number">06 / Autonomous UAV</span></div>
    <h1 class="case-title">Agentic Pollination UAV</h1><p class="case-summary">A cyber-physical framework for precision pollination through integrated computer vision, mission-level reasoning, and embedded mechatronic actuation.</p>
    <p class="research-byline">Mohammad Zoraiz · Dr. Martin Brooke · Yasha Saxena · Jackie Ong · Gianluca Zambrano · Anika Suman</p>
    <div class="case-actions"><a class="button button-primary" href="${project.repo}" target="_blank" rel="noreferrer">Code <span>↗</span></a><a class="button button-quiet" href="#results">Results <span>↓</span></a><a class="button button-quiet" href="#reproducibility">Data <span>↓</span></a></div><div class="case-tags">${tags}</div></div>
    <figure class="research-cover-media abstract-cover"><img src="../assets/projects/covers/agentic-pollination-uav.png" alt="Minimal botanical flight-path poster for Agentic Pollination UAV"><figcaption>Perception · planning · pollination</figcaption></figure>
  </div></section>
  <nav class="research-toc uav-toc" aria-label="On this page"><a href="#overview">Introduction</a><a href="#architecture">Architecture</a><a href="#reasoning">Reasoning</a><a href="#results">Experiments</a><a href="#hardware">Hardware</a><a href="#limitations">Limitations</a></nav>

  <section class="research-metrics" aria-label="Key project facts"><div><strong>13</strong><span>mission phases</span></div><div><strong>8 / 8</strong><span>simulation targets</span></div><div><strong>20 Hz</strong><span>hardware mission loop</span></div><div><strong>24</strong><span>physical sensor samples</span></div></section>

  <article class="research-prose" id="overview"><p class="section-index">01 / Introduction</p><h2>Closing the loop from perception to pollen delivery</h2>
    <p>Pollination in degraded or hard-to-reach environments is a coupled robotics problem. The aircraft must discover candidate flowers, choose a route, descend into a sensor-stable hover, deliver pollen, and recover safely. This project implements that complete loop across a browser simulation and a Raspberry Pi/Pixhawk hardware path.</p>
    <p>The central design choice is separation of authority. A tool-using language agent may recommend routes, scan spacing, and confidence thresholds; a deterministic 13-phase state machine retains control over flight, alignment, actuation, return-to-home, and landing.</p>
    <aside class="research-callout"><span>Evidence boundary</span><p>The 8/8 result is a seeded 90-second simulation. The repository contains hardware interfaces and physical bench/flight tests, but no autonomous outdoor mission log. Those evidence tiers are reported separately below.</p></aside>
  </article>

  <figure class="research-figure technical-diagram" id="architecture"><div class="diagram-viewport"><object data="../assets/projects/agentic-pollination-uav/figures/system-overview.svg" type="image/svg+xml" aria-label="Hardware, perception, bounded decision, and pollination action layers"></object></div><figcaption><strong>System overview.</strong> Camera, flight controller, embedded compute, accelerator, actuation, and navigation feed a bounded perception–decision–action loop. <span class="diagram-hint"><span class="desktop-hint">Hover a module to inspect the flow.</span><span class="mobile-hint">Swipe to explore the complete diagram.</span></span></figcaption></figure>

  <section class="research-wide research-section"><p class="section-index">02 / System design</p><h2>One interface, two execution paths</h2><div class="research-comparison">
    <article><span>Replay mode</span><h3>Deterministic evaluation</h3><p>2,700 pre-generated frames encode a 90-second mission at 30 fps. One frame index drives every dashboard panel, enabling repeatable seeking and visual regression checks.</p></article>
    <article><span>Live mode</span><h3>Closed-loop simulation</h3><p>A real-time navigator exchanges state with WebSocket inference, requests an agent decision once per second, streams commentary, and persists completed mission context.</p></article>
  </div></section>
  <figure class="research-figure technical-diagram"><div class="diagram-viewport"><object data="../assets/projects/agentic-pollination-uav/figures/mission-pipeline.svg" type="image/svg+xml" aria-label="Hierarchical autonomous mission pipeline"></object></div><figcaption><strong>Hierarchical autonomy.</strong> Bounded agent recommendations feed a deterministic 13-phase controller with telemetry feedback and explicit safety guards. <span class="diagram-hint"><span class="desktop-hint">Hover a service or phase group to inspect it.</span><span class="mobile-hint">Swipe to explore the complete diagram.</span></span></figcaption></figure>

  <article class="research-prose" id="reasoning"><p class="section-index">03 / Adaptive reasoning</p><h2>Learning when confidence is sufficient</h2>
    <p>A contextual UCB1 bandit chooses among detection thresholds 0.40, 0.60, and 0.75. Mission phase, optical-flow stability, and battery state define the context. Each action balances observed reward with an exploration bonus:</p>
    <div class="equation-block" role="math" aria-label="UCB of action a equals cumulative reward divided by action count plus square root of two log total selections divided by action count">UCB(a) = R<sub>a</sub> / N<sub>a</sub> + √(2 ln N / N<sub>a</sub>)</div>
    <p>Mission memory uses Chroma and local all-MiniLM-L6-v2 embeddings. Before each decision, the three most similar completed missions are retrieved and inserted as context. Tool execution is limited to three rounds and can invoke route, battery-range, confidence-threshold, and scan-pattern functions.</p>
    <h3>Sensor-aware confidence</h3><p>Optical-flow measurements are interpolated with smoothstep easing, <span class="inline-equation">s(t)=t²(3−2t)</span>. Detection confidence is then coupled to stability and signal strength:</p>
    <div class="equation-block">c′ = c · (0.6 + 0.4s) · (0.6 + 0.4q/255)</div>
    <p>Below 50 flow-quality units, an additional 0.6 multiplier models an unreliable estimate. Stable hover below 3 m receives a 15% boost. These deterministic couplings make replay results reproducible while retaining behavior grounded in 24 physical optical-flow samples.</p>
  </article>

  <figure class="research-figure dashboard-figure"><div class="dashboard-grid"><img src="../assets/projects/agentic-pollination-uav/screens/dashboard-live-mode.png" alt="Live mission dashboard showing route, altitude, telemetry, camera analysis, and optical-flow readings"><img src="../assets/projects/agentic-pollination-uav/screens/topdown-tsp-route.png" alt="Top-down garden view with numbered targets and the planned TSP route"></div><figcaption><strong>Mission interface.</strong> A common view exposes route state, altitude, telemetry, perception, optical flow, agent decisions, terminal events, and the current visit order.</figcaption></figure>

  <section class="research-wide research-section" id="results"><p class="section-index">04 / Experiments</p><h2>What constrains the system?</h2><p class="research-lede">The current checked-in run benchmarks algorithmic cost on a development machine—not Raspberry Pi hardware. The important result is not raw throughput; it is that approach geometry and sensor confidence constrain the mission before route-planning compute does.</p>
    <div class="result-table-wrap"><table class="result-table"><thead><tr><th>Experiment</th><th>Measured result</th><th>Interpretation</th></tr></thead><tbody>
      <tr><td>Mock detector · hover · 8 flowers</td><td>7.1 µs mean</td><td>Simulation detector cost is negligible.</td></tr><tr><td>Full 2,700-frame pipeline</td><td>59,571 fps · 16.6 µs mean</td><td>1,986× the 30 fps simulation target.</td></tr><tr><td>Optical-flow interpolation</td><td>504,218 lookups/s</td><td>Sensor lookup is not the loop bottleneck.</td></tr><tr><td>Greedy TSP · 8 targets</td><td>8.6 µs mean · 8.8 µs p95</td><td>O(n²) planning remains cheap at mission scale.</td></tr><tr><td>0.75 confidence lock</td><td>2.55 m at 0 m offset</td><td>Not reached at 1, 2, or 4 m offset.</td></tr><tr><td>UCB1 policy · 500 steps</td><td>230 lock-level selections · reward 242</td><td>The policy explores all three threshold arms.</td></tr><tr><td>LLM decision latency</td><td>Not measured</td><td>Skipped because no API key was supplied.</td></tr>
    </tbody></table></div>
  </section>
  <div class="research-gallery"><figure><img src="../assets/projects/agentic-pollination-uav/figures/b3_tsp_scalability.png" alt="Greedy TSP latency by flower count"><figcaption>TSP scalability from 2 to 50 targets.</figcaption></figure><figure><img src="../assets/projects/agentic-pollination-uav/figures/b5_confidence_altitude.png" alt="Detection confidence by altitude and horizontal offset"><figcaption>Confidence lock depends strongly on approach alignment.</figcaption></figure><figure><img src="../assets/projects/agentic-pollination-uav/figures/b2_sensor_interpolation.png" alt="Optical-flow interpolation based on measured samples"><figcaption>Interpolation is grounded in 24 physical samples.</figcaption></figure><figure><img src="../assets/projects/agentic-pollination-uav/figures/b6_bandit_convergence.png" alt="UCB1 threshold selection and cumulative reward"><figcaption>UCB1 explores three confidence-threshold arms.</figcaption></figure></div>

  <section class="research-wide research-section" id="hardware"><p class="section-index">05 / Physical system</p><h2>From browser model to aircraft</h2><div class="hardware-layout"><figure><img src="../assets/projects/agentic-pollination-uav/figures/hardware-annotated.jpg" alt="Annotated F450 drone and pollen-delivery mechanism"></figure><div><p>The prototype combines an F450 quadcopter, Pixhawk 2.4.8, Raspberry Pi 4, Coral USB accelerator, downward camera, optical-flow sensor, GPS/compass, and servo-driven dispenser.</p><ul><li>Camera-only plant detection: 9 / 10 trials</li><li>Camera mounted on assembled drone: 4 / 4 trials</li><li>Raspberry Pi bench detection: approximately 30 fps with stable servo operation</li><li>More than 1 g of flour substitute delivered into a test flower</li><li>Stable manual flight demonstrated within 5 feet of ground level</li></ul><p class="caption">These report physical and bench-validation results, not autonomous outdoor pollination.</p></div></div></section>

  <figure class="research-figure field-test-figure"><img src="../assets/projects/agentic-pollination-uav/figures/physical-system-test.jpg" alt="Research team member testing the assembled pollination UAV above three flowering plants in the Duke Foundry"><figcaption><strong>Physical system test.</strong> Evaluating the assembled aircraft, camera placement, and pollen-delivery workflow against representative flowering plants in The Foundry.</figcaption></figure>

  <figure class="research-figure poster-figure"><img src="../assets/projects/agentic-pollination-uav/figures/research-poster.jpg" alt="Duke Pratt engineering poster for the cyber-physical pollination UAV"><figcaption><strong>Engineering poster.</strong> Presented through Duke Pratt School of Engineering, The Foundry, and the Pierre R. Lamond Department of Electrical &amp; Computer Engineering.</figcaption></figure>

  <article class="research-prose" id="limitations"><p class="section-index">06 / Conclusions &amp; limitations</p><h2>A credible path, with an unfinished autonomy gap</h2><ul class="research-limitations"><li><strong>Simulation fidelity.</strong> The 8/8 completion result comes from seeded synthetic scenes and should not be generalized to field success.</li><li><strong>Timing portability.</strong> Benchmark timings characterize the development machine; Raspberry Pi and Coral end-to-end latency requires separate measurement.</li><li><strong>Agent evaluation.</strong> LLM decision latency and comparative mission benefit were not measured in the checked-in run.</li><li><strong>Outdoor validation.</strong> Wind, illumination, occlusion, plant motion, localization error, and ecological safety remain open validation requirements.</li></ul></article>

  <section class="research-wide research-section reproducibility-block" id="reproducibility"><p class="section-index">07 / Reproducibility</p><h2>Inspect the evidence</h2><p class="research-lede">The benchmark suite can be regenerated with <code>python benchmark_suite.py</code>. The portfolio checks in the exact plots and underlying JSON/CSV used on this page.</p><div class="case-actions"><a class="button button-primary" href="${project.repo}" target="_blank" rel="noreferrer">Open repository <span>↗</span></a><a class="button button-quiet" href="../assets/projects/agentic-pollination-uav/data/benchmark_results.json">Benchmark JSON <span>↓</span></a><a class="button button-quiet" href="../assets/projects/agentic-pollination-uav/data/raw_opticalflow_data.csv">Sensor CSV <span>↓</span></a></div></section>
  <a class="case-next" href="ctrlslash.html"><span>Next project / 07</span><strong>CtrlSlash →</strong></a>`;

document.querySelector("main").innerHTML = slug === "ombench" ? ombenchPage : slug === "quantum-bayesian-learner" ? quantumBayesianPage : slug === "targetonco" ? targetOncoPage : slug === "agentic-pollination-uav" ? uavPage : `
  <section class="project-cover" id="first-content"><div class="case-hero research-cover-grid">
    <div class="blog-intro"><div class="case-kicker"><a class="project-back" href="../projects.html">← All projects</a><span class="case-number">${project.number} / ${project.category}</span></div>
    <h1 class="case-title">${project.title}</h1><p class="case-summary">${project.summary}</p><p class="research-byline">Mohammad Zoraiz · Research &amp; Engineering</p>
    <div class="case-actions"><a class="button button-primary" href="${project.repo}" target="_blank" rel="noreferrer">Code <span>↗</span></a><a class="button button-quiet" href="#overview">Overview <span>↓</span></a></div><div class="case-tags">${tags}</div></div>
    <figure class="research-cover-media abstract-cover"><img src="../assets/projects/covers/${slug}.png" alt="Minimal geometric research poster for ${project.title}"><figcaption>${project.category}</figcaption></figure>
  </div></section>
  <nav class="research-toc" aria-label="On this page"><a href="#overview">Overview</a><a href="#system">System</a><a href="#principles">Principles</a><a href="#status">Status</a></nav>
  <section class="case-canvas" id="system" aria-label="${project.title} system flow"><p class="section-index">System flow</p>${systemVisual}</section>
  <div class="case-body">
    <section class="case-row" id="overview"><p class="case-row-label">01 / The problem</p><div class="case-copy"><h2>Why this exists</h2><p>${project.problem}</p></div></section>
    <section class="case-row"><p class="case-row-label">02 / The approach</p><div class="case-copy"><h2>One connected system</h2><p>${project.approach}</p></div></section>
    <section class="case-row" id="principles"><p class="case-row-label">03 / Design principles</p><div class="case-copy"><h2>How the work is shaped</h2><div class="case-columns">${notes}</div></div></section>
    <section class="case-row" id="status"><p class="case-row-label">04 / Current state</p><div class="case-copy"><h2>A starting point</h2><p>${project.status}</p></div></section>
  </div>
  <a class="case-next" href="${project.next}.html"><span>Next project / ${next.number}</span><strong>${next.title} →</strong></a>`;

if (slug === "targetonco" || slug === "quantum-bayesian-learner") {
  const lightbox = document.createElement("dialog");
  lightbox.className = "diagram-lightbox";
  lightbox.setAttribute("aria-label", "Expanded architecture diagram");
  lightbox.innerHTML = `<button class="diagram-lightbox-close" type="button" aria-label="Close expanded diagram">Close <span>×</span></button><div class="diagram-lightbox-scroll"><img alt=""></div>`;
  document.body.appendChild(lightbox);

  const expandedImage = lightbox.querySelector("img");
  const closeButton = lightbox.querySelector(".diagram-lightbox-close");
  const closeLightbox = () => lightbox.close();

  document.querySelectorAll(".target-reference-diagram img, .qbl-source-figure img, .qbl-gallery img").forEach((image) => {
    image.tabIndex = 0;
    image.setAttribute("role", "button");
    image.setAttribute("aria-label", `${image.alt}. Open enlarged view.`);
    const openLightbox = () => {
      expandedImage.src = image.src;
      expandedImage.alt = image.alt;
      lightbox.showModal();
      closeButton.focus();
    };
    image.addEventListener("click", openLightbox);
    image.addEventListener("keydown", (event) => {
      if (event.key === "Enter" || event.key === " ") {
        event.preventDefault();
        openLightbox();
      }
    });
  });

  closeButton.addEventListener("click", closeLightbox);
  lightbox.addEventListener("click", (event) => {
    if (event.target === lightbox) closeLightbox();
  });
}
